### ISSUE TITLE
digga's mkFlake complains when vscode is exported via vs-ext.overlay

### ISSUE THREAD

**Issue by danielphan2003** [divnix/vs-ext#3]
Nix throws the following error:
```
error: attempt to call something which is not a function but a set

       at /nix/store/d3vlpgh54ackhc03fdcn9pqh5q3cgkcp-source/lib/exportOverlays.nix:63:42:

           62|       channelNames = attrNames channels;
           63|       overlayNames = overlay: attrNames (overlay null null);
             |                                          ^
           64|
```

Temporary workaround is to remove vs-ext from inputs, like so: `inputs = builtins.removeAttrs inputs [ "vs-ext" ];`

@GTrunSec I saw your nixos-flk config, and I have no idea why flake-utils-plus keeps complaining ;(

**Comment by GTrunSec** [comment]
Do you have a reproducible rev for that ?

![image](https://user-images.githubusercontent.com/21156405/143319993-c3eb05e5-f4f0-4f63-aa19-26f02f8f20ae.png)

**Comment by danielphan2003** [comment]
Maybe it was a fluke, but everything now works as intended.
